### ISSUE TITLE
Test String SCALE Encoding/Decoding

### ISSUE THREAD

**Issue by ansermino** [ChainSafeSystems/gossamer#25]
## Expected Behavior

N/A

## Current Behavior

N/A

## Possible Solution

Write tests for encoding/decoding strings with SCALE. Encoding/decoding strings has been implicitly implemented via `encodeBytes`, minor adjustments to implementation may be required to expose this before tests can be written.

## Steps to Reproduce (for bugs)

N/A

## Your Environment
* Version used:
* Commit hash:
* Go Version:
* Operating System and version (include distro if Linux):
* Link to your project or reproducible gist:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by amerameen** [comment]
@ansermino @noot

Looking for feedback on testString3 on commit a0020e3.

Referencing this doc: https://gist.github.com/ansermino/8a0dcb394648ac55b537dca2fde2e9fe

testString3 is meant to test the case where 2^30 <= n < 2^536. However, m (num of bytes for n) is 3 bytes long, so I'm getting k_1 := m - 4 as a negative number. Do we just pad the num of bytes to a minimum 4 bytes here?

See comments around testString3 for my calculations.

**Comment by ansermino** [comment]
@amerameen I fail to see how a negative number is possible. `n` must be `>= 2^30` which means it has at least 4 bytes, thus `m-4 >= 0`. We should perhaps clarify whether it should actually be 1, although counting from 0 would be the most compact

**Comment by noot** [comment]
m must be at least 4, it shouldn't be negative. if it is then we are still in the previous mode
