### ISSUE TITLE
Setup K/V Data Store

### ISSUE THREAD

**Issue by ansermino** [ChainSafeSystems/gossamer#32]
- [x] Determine the best k/v store to utilize
- [x] Setup k/v store 
- [x] Setup basic operations
- [x] Unit tests for operations
- [x] Setup memory database
- [x] Unit tests for memory database ops
- [x] Set up Batch writes
- [x] Unit tests for batch writes
- [x] Set up Iterator
- [x] Unit tests for iterator

**Comment by dutterbutter** [comment]
https://github.com/ethereum/go-ethereum/issues/15717

**Comment by dutterbutter** [comment]
Batch writes and iterator functionality has been implemented, need to add tests and provide interfaces for exported functions
