### ISSUE TITLE
Test SCALE Against Parity Codec

### ISSUE THREAD

**Issue by ansermino** [ChainSafeSystems/gossamer#33]
Ensure our implementation complies with parity's

**Comment by drskalman** [comment]
I have written this test to run and compare of the result of gossamer SCALE codec with the parity implementation of the codec:

https://github.com/w3f/polkadot-re-tests/blob/master/test/scale_codec_tests.jl

 and I don't get equality:

    Test Summary:                  | Pass  Fail  Total
    Scale Codec Tests              |    6     6     12
    Scale codec byte arrey tests |    6     6     12

Getting for example:

      1
      encoded 1: MQ==
      1
      encoded 1: BDE=
      Scale codec byte arrey tests: Test Failed at /home/klaymen/doc/code/polkadot-re-tests/test/scale_codec_tests.jl:12
      Expression: test_result_array[end] == test_result_array[1]

I'm not sure what is the problem but it would be awesome if you could look into it and make the tests pass.

**Comment by ansermino** [comment]
Will look into this :+1:

**Comment by ansermino** [comment]
@drskalman Can you please provide some further explanation. There are only 6 test cases, yet there are 6 passes and 6 fails? We assumed it is outputting the ascii/unicode interpretation of the hex values but that doesn't seem to correlate to the expected output. We got the tests running but some documentation in the repo would go a long way.

**Comment by ansermino** [comment]
After modifying the output to show hex it is apparent the parity-codec is using fixed width integer encoding. Perhaps this is a bug in the tester? Would expect it not to use fixed width if a byte array is passed in.

```
encoded 1: 1
1
encoded 1: 0431
Scale codec byte arrey tests: Test Failed at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:12
  Expression: test_result_array[end] == test_result_array[1]
   Evaluated: Process(`sh -c 'testers/go-tester/scale_codec/scale_codec encode  --input "1"'`, ProcessExited(0)) == Process(`sh -c 'testers/rust-tester/target/debug/scale_codec encode  --input "1"'`, ProcessExited(0))
Stacktrace:
 [1] top-level scope at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:12
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:4
22
encoded 22: 22
22
encoded 22: 083232
Scale codec byte arrey tests: Test Failed at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:12
  Expression: test_result_array[end] == test_result_array[1]
   Evaluated: Process(`sh -c 'testers/go-tester/scale_codec/scale_codec encode  --input "22"'`, ProcessExited(0)) == Process(`sh -c 'testers/rust-tester/target/debug/scale_codec encode  --input "22"'`, ProcessExited(0))
Stacktrace:
 [1] top-level scope at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:12
 [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
 [3] top-level scope at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:4
333
encoded 333: 333
333
encoded 333: 0c333333
Scale codec byte arrey tests: Test Failed at /home/elizabeth/polkadot-re-tests/test/scale_codec_tests.jl:12
  Expression: test_result_array[end] == test_result_array[1]
   Evaluated: Process(`sh -c 'testers/go-tester/scale_codec/scale_codec encode  --input "333"'`, ProcessExited(0)) == Process(`sh -c 'testers/rust-tester/target/debug/scale_codec encode  --input "333"'`, ProcessExited(0))
```

**Comment by drskalman** [comment]
As @ansermino pointed out rust tester was not calling encode at all. https://github.com/w3f/polkadot-re-tests/commit/ea1567030646220e5560cda6e2b5b3ddde405862 fixes that which fixes this issue:

    Test Summary:     | Pass  Total
    Scale Codec Tests |    6      6
      0.111596 seconds (3.28 k allocations: 2.471 MiB, 4.16% gc time)
      0.118408 seconds (3.49 k allocations: 2.482 MiB, 3.92% gc time)
    Test.DefaultTestSet("Scale Codec Tests", Any[DefaultTestSet("Scale codec byte arrey tests", Any[], 6, false)], 0, false)

**Comment by noot** [comment]
@drskalman amazing :)
