### ISSUE TITLE
Implement SCALE support for Strings

### ISSUE THREAD

**Issue by ansermino** [ChainSafeSystems/gossamer#35]

**Comment by amerameen** [comment]
Looking for feedback on testString3 on commit af1ae2e28d2b70a9de52da4035d1cf7fe3a679fc.

Referencing this doc: https://gist.github.com/ansermino/8a0dcb394648ac55b537dca2fde2e9fe

testString3 is meant to test the case where 2^30 <= n < 2^536. However, m (num of bytes for n) is 3 bytes long, so I'm getting k_1 := m - 4 as a negative number. Do we just pad the num of bytes to a minimum 4 bytes here?

See comments around testString3 for my calculations.

**Comment by amerameen** [comment]
Added SCALE support on this commit: e78ae99021078f025bdceb631ac2765a46f6ca68.

Will submit PR with full testing, see #25.
