### ISSUE TITLE
Add flag to omit long running tests on the CI

### ISSUE THREAD

**Issue by amerameen** [ChainSafeSystems/gossamer#60]
Tests that are large in size (such as testString3 in encode_test.go) cause the CI to fail since the tests take too long to run.

It would be helpful to have a flag to denote which tests the CI should avoid running.

**Comment by GregTheGreek** [comment]
👋 Hi Hi I'll take this on expect a PR in a day or two :)

**Comment by ansermino** [comment]
@GregTheGreek lets look at Travis as an alternative to this. Having issues with #66

**Comment by GregTheGreek** [comment]
Definitely running out of memory on travis BUT I'm looking into solutions.

**Comment by ansermino** [comment]
Possible alternative: https://www.appveyor.com/ (thanks @dutterbutter)

**Comment by GregTheGreek** [comment]
I have a branch with travis and appveyor (appveyor is giving me some troubles) `greg/travis` 

I read some materials, appveyor is commonly used to test for windows environments, but they have support for ubuntu so I'm working on it.

Later on, we can seperate concerns, use Circle and Travis for ubuntu osx and appveyor for windwos testing
